version: '3.4'
services:
  client:
    container_name: fullstack_client
    stdin_open: true
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000
    environment:
      CHOKIDAR_USEPOLLING: 'true'

  server:
    container_name: fullstack_server
    stdin_open: true
    build: 
      context: ./server
    depends_on:
      - database
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 5000:5000
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    
  database:
    image: mongo:latest
    container_name: fullstack_database
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fullstack
      
volumes:
  mongo-data: