version: '3.4'
services:
  client:
    container_name: fullstack_client
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000
    networks: 
      - frontend

  server:
    container_name: fullstack_server
    build: 
      context: ./server
    depends_on:
      - database
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 5000:5000
    networks: 
      - backend
    
  database:
    image: mongo:latest
    container_name: fullstack_database
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fullstack
    networks: 
      - backend
      
volumes:
  mongo-data:

networks:
  frontend:
  backend: