version: '3.4'
services:
  client:
    container_name: fullstack_client
    build: 
      context: ./client
    depends_on:
      - server
    volumes:
      - ./client:/app/client
      - /app/client/node_modules
    ports:
      - 3000:3000
    networks: 
      - frontend

  server:
    container_name: fullstack_server
    build: 
      context: ./server
    depends_on:
      - database
      - redis
    volumes:
      - ./server:/app/server
      - /app/server/node_modules
    ports:
      - 5000:5000
    networks: 
      - backend
    
  database:
    image: mongo:4.4.2
    container_name: fullstack_database
    depends_on:
      - redis
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=fullstack
    networks: 
      - backend

  redis:
    image: redis:6.0.9
    container_name: fullstack_redis
    volumes:
      - redis-data:/data/redis
    ports:
      - 6379:6379
    networks:
      - backend
      
volumes:
  mongo-data:
  redis-data:

networks:
  frontend:
  backend: